apiVersion: v1 
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 3000 
  type: LoadBalancer