
name: Deploy to AKS Cluster 

on:
  push:
    branches: ['main']

jobs:
  build-and-push-dockerhub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build Docker image
        run: |
            docker build -t kkrdocker6589/weather:${{ github.sha }} .
        
      - name: Push Docker image
        run: |
            docker push kkrdocker6589/weather:${{ github.sha }}

  deploy_to_AKS:
    needs: build-and-push-dockerhub
    runs-on: ubuntu-latest
    steps:      
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure
        env:
            AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        run: |
            echo $AZURE_CREDENTIALS | az login --service-principal --username $(echo $AZURE_CREDENTIALS | jq -r .clientId) --password $(echo $AZURE_CREDENTIALS | jq -r .clientSecret) --tenant $(echo $AZURE_CREDENTIALS | jq -r .tenantId)
  
      - name: Set AKS Credentials
        run: |
            az aks get-credentials --resource-group ${{ secrets.RESOURCE_GROUP }} --name ${{ secrets.AKS_CLUSTER_NAME }}

      - name: Set kubectl context
        run: |
              kubectl config use-context TG-APP-UP            
            
      - name: Install Helm
        run: |
            curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
        
      - name: Create Image Pull Secret
        run: |
              kubectl get secret my-dockerhub-secret -n default || \
              kubectl create secret docker-registry my-dockerhub-secret \
                --docker-username=${{ secrets.DOCKER_USERNAME }} \
                --docker-password=${{ secrets.DOCKER_PASSWORD }} \
                --docker-email=${{ secrets.DOCKER_EMAIL }}

      - name: Deploy Helm Chart
        run: |
              helm upgrade --install basic-react-app ./basic-helm \
                --set image.repository=${{ secrets.DOCKER_IMAGE }} \
                --set image.tag=${{ github.sha }}
